version: '3.7'

x-common-dev-settings:
  &common-dev-settings
  CERYX_DEBUG: ${CERYX_DEBUG:-true}

services:
  ceryx:
    build: ./ceryx
    volumes:
      - ./ceryx/nginx/conf:/usr/local/openresty/nginx/conf
      - ./ceryx/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./ceryx/static:/etc/ceryx/static
    environment:
      <<: *common-dev-settings
      CERYX_DOCKERIZE_EXTRA_ARGS: ""

  api:
    build: ./api
    volumes:
      - ./api:/opt/ceryx
    environment:
      <<: *common-dev-settings
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-api.ceryx.dev}
    command: uvicorn --reload --host 0.0.0.0 --port 5555 api:api

networks:
  default:
    driver: bridge  # Use a Bridge network for local development
    name: ceryx
